name: Rust CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 🚀 Rust CI
    if: github.repository == 'FrilLab/dustfril'
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout sources
        uses: actions/checkout@v6

      - name: 🦀 Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📦 Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: ✅ Cargo Check
        run: cargo check --all

      - name: 🚨 Cargo Fmt
        run: cargo fmt --all -- --check

      - name: 🚨 Cargo Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: 🧪 Cargo Test
        run: cargo test --workspace
