name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 🚀 Rust CI
    if: github.repository == 'FrilLab/dustfril'
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev

      - name: 🦀 Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📦 Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: 🚨 Cargo Fmt
        run: cargo fmt --all -- --check

      - name: 🚨 Cargo Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: 🧪 Cargo Test
        run: cargo test --workspace
